version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: novelai-backend
    env_file:
      - .env
    volumes:
      - ./data:/root/data
    networks:
      - novelai-network
    restart: unless-stopped
    # 不暴露端口到主机，只在内部网络中可访问

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: novelai-frontend
    ports:
      - "3333:3000"
    depends_on:
      - backend
    networks:
      - novelai-network
    restart: unless-stopped

networks:
  novelai-network:
    driver: bridge

volumes:
  data:
    driver: local
